name: abeci
dependencies:
  - python=3.10
  - pip=21.2.4
  - pip:
    - google-ngram-downloader==4.0.1
    - unidecode==1.3.4
    - requests==2.27.1
    - urllib3==1.26.8
    - sympy==1.8
    - pyyaml==6.0
