package:
    name: abeci
    version: "1.0.0"
source:
    git_url: https://github.com/ilanschnell/bsdiff4.git
    git_rev: "1.0.0"
build:
    entry_points:
        - src.pangrams:pangramsCli
requirements:
  build:
    - git
  host:
    - python
    - pip
    - google-ngram-downloader >=4.0.1
    - unidecode >=1.3.4
    - requests >=2.27.1
    - urllib3 >=1.26.8
    - sympy >=1.8
    - pyyaml >=6.0
  run:
    - python
test:
  requires:
    - unittest
  imports:
    - abeci
about:
  license: MIT
  summary: "Find perfect pangrams."
  home: https://github.com/tvquizphd/abeci
